# Generated by Django 4.0.2 on 2022-04-06 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('exchange', models.CharField(max_length=30)),
                ('buy_price', models.FloatField()),
                ('buy_date', models.DateField(default=django.utils.timezone.now)),
                ('sell_price', models.FloatField()),
                ('sell_date', models.DateField()),
                ('pnl', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
