# Generated by Django 4.0.2 on 2022-05-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_investment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='sell_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='sell_price',
            field=models.FloatField(null=True),
        ),
    ]
