# Generated by Django 4.0.2 on 2022-05-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_alter_investment_sell_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='pnl',
            field=models.FloatField(null=True),
        ),
    ]
