# Generated by Django 4.0.2 on 2022-06-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_alter_investment_pnl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='pnl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='sell_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='sell_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
